# Generated by Django 5.2.6 on 2025-12-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_image_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
