# Generated by Django 5.2.6 on 2026-01-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OUTBID', 'Outbid'), ('WON', 'Won'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
