# Generated by Django 5.2.6 on 2026-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OUTBID', 'Outbid'), ('WON', 'Won')], default='PENDING', max_length=20),
        ),
    ]
